TYPE = "controllerType"
ID = "id"
CHILDREN = "childrens"
GET_VALUE = "getValue"
SERVER_ADDRESS = ""
SIZE = "size"
COLOR = "color"
TEXT = "text"
IDENTITY = "identity"
DEVICE_NAME = "deviceName"
DEVICE_DESCRIPTION = "deviceDescription"

CMD_SET_TEXT = "settext_"
